### ISSUE TITLE
grunt-exorcise no longer detects latest browserify inline sourcemap

### ISSUE THREAD

**Issue by darrennolan** [mikefrey/grunt-exorcise#10]
Seems to be resolved in 0.4.0 of exorcist.

Using grunt-browserify which is loading browserify v10. (10.2.0)

Start `//# sourceMappingURL=data:application/json;charset:utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3`...

Previous version of exorcist declares no inline source and skips over it whereas version 0.4.0 detects and removes as required.

Looking into pull request shortly to make this easier for you but just double checking tests.

**Comment by mikefrey** [comment]
@darrennolan A PR would be much appreciated. Thank you!

**Comment by HenriqueSilverio** [comment]
Maybe the same here?
![](http://i.imgur.com/SuIFklu.png)

**Comment by darrennolan** [comment]
Same issue, yes.  But you haven't updated the tests associated, which do fail now on the new version of exorcist.  I've forked but not yet had a chance to update the tests to reflect the new output.  (Which is mostly from what I've seen whitespace changes).

**Comment by HenriqueSilverio** [comment]
Humm really... @darrennolan some tip to help me fix that?

**Comment by darrennolan** [comment]
@HenriqueSilverio - run `npm test` and you'll see that the test are failing.  We'll be looking further into that a bit on this week.

In the meantime everyone - please use @HenriqueSilverio's fork or look to use `"grunt-exorcise": "git+https://github.com/FoxSportsAustralia/grunt-exorcise.git#1.1.0"` in your package.json for the immediate short-term.

I'll update this issue as soon as we push our update for the tests.

**Comment by Tritlo** [comment]
+1

**Comment by darrennolan** [comment]
@mikefrey - I didn't get a chance to thank you for updating and fixing the test.

Thank you!

**Comment by mikefrey** [comment]
I didn't fix it, @crgwbr did. Thank him!

**Comment by darrennolan** [comment]
Thanks @crgwbr!
Thank you @mikefrey for the project though =D
