### ISSUE TITLE
Crashes if the source doesn't exist.

### ISSUE THREAD

**Issue by AsaAyers** [mikefrey/grunt-exorcise#5]
You have a check for it, but on line 32 it uses `file.src[0].cyan`, but if the file doesn't exist `file.src[0]` is undefined.

This also seems like a very strange place to store the color, and I don't see where it's documented in Grunt's docs. Are you sure `file.src[0].cyan` is the right place to get the color?

https://github.com/mikefrey/grunt-exorcise/blob/master/tasks/exorcise.js#L32-L38

**Comment by mikefrey** [comment]
It's probably good if it aborts without a valid src. But the way it aborts is bad. So here's a PR that should fix it: https://github.com/mikefrey/grunt-exorcise/pull/7
